name: Build and Publish

on:
  push:
    branches:
      - '*' # all branches
    tags:
      - 'v*' # all tags starting with v

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'


      - run: npm install
      - run: npm test

      - name: publish
        if: github.ref_type == 'tag'
        run: |
          npm version from-git --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}